# Generated by Django 2.2.5 on 2020-12-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterApp', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
