# Generated by Django 2.2.5 on 2020-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterApp', '0006_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
